[package]
name = "mag-service"
version.workspace = true
edition.workspace = true

[features]
default = []
ts-export = ["dep:ts-rs", "mag-config/ts-export"]

[dependencies]
async-trait.workspace = true
futures.workspace = true
mag-config = { path = "../mag-config" }
serde.workspace = true
serde_json.workspace = true
ts-rs = { workspace = true, optional = true, features = ["no-serde-warnings", "serde-json-impl", "uuid-impl"] }
uuid.workspace = true
