[package]
name = "mag-web"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
futures.workspace = true
mag-service = { path = "../mag-service" }
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tower = { workspace = true, features = ["util"] }
