[package]
name = "mag-config"
version.workspace = true
edition.workspace = true

[features]
default = []
ts-export = ["dep:ts-rs"]

[dependencies]
serde.workspace = true
serde_yml.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing = "0.1"
ts-rs = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
